### ISSUE TITLE
Support namespaced keywords

### ISSUE THREAD

**Issue by ghost** [amperity/envoy#10] opened 2018-12-04 17:20 UTC
It would be nice if the following would work:
```clj
(ns myenv (:require [envoy.core :refer [defenv]]))
(defenv ::the-var "The var" :type :string)
(ns other (:require [envoy.core :refer [env]] [myenv :as env]))
(env ::env/the-var)
```

Currently, they are treated as undeclared:
```
[envoy.check:286] - Overriding undeclared env variable :envoy.core/the-var
```

**Comment by aengelberg** [comment] 2018-12-04 17:34
Hmm, I'm not able to reproduce this:
```clojure
user=> (ns myenv (:require [envoy.core :refer [defenv]]))
nil
myenv=> (defenv ::the-var "The var" :type :string)
{:description "The var", :line 1, :ns myenv, :type :string}
myenv=> (ns other (:require [envoy.core :refer [defenv]] [myenv :as env]))
nil
other=> (envoy.core/env ::env/the-var)
nil
```

**Comment by sonntag** [comment] 2018-12-04 18:04
@urzds it looks like you may have a namespace conflict somewhere. Check in your code to see if you have a require with `[envoy.core :as env]` somewhere. 

The error message you provided is saying that the `::env/the-var` keyword is being expanded to `:envoy.core/the-var` instead of `:myenv/the-var` as you expect.

**Comment by ghost** [comment] 2018-12-04 18:15
@sonntag: I also just figured that out. It happened that two different issues were mixed and confused me. Thanks!

The second, more severe, issue persists, though:
```
dev=> (ns myenv (:require [envoy.core :refer [defenv]]))
nil
myenv=> (defenv ::user "The var" :type :string)
{:type :string, :ns myenv, :line 3, :description "The var"}
myenv=> (ns other (:require [envoy.core :refer [env]] [myenv :as env]))
nil
other=> (env ::env/user)
nil
other=> (env :user)
2018-12-04 18:06:12.727+0000 <HOSTNAME> WARN [envoy.check:286] - Access to undeclared env variable :user
"<USERNAME>"
```

So `:user` gives me the value of `$USER`, but `::env/user` gives me nothing.

Reading [environ.core](https://github.com/weavejester/environ/blob/master/environ/src/environ/core.clj), it seems that when reading from `.lein-env` or `.boot-env` into `environ.core/env`, namespaces are stripped. Environment variables never contain "namespaces". Hence `environ` contains no code to handle them during lookup and probably does not intend to, since `environ.core/env` is just a plain map.

Thus the lookup should probably be fixed up in `envoy.core/env`'s wrapper around `environ.core/env`, since it already contains other logic, so adding a `(name k)` doesn't hurt.

**Comment by aengelberg** [comment] 2018-12-04 18:52
I think the behavior you're seeing is appropriate. Since `:myenv/user` and `:user` are distinct keys, looking them up in a map should yield different results. In weavejester/environ#67, weavejester clarifies that environ's stripping of namespaces from `.lein-env` is intentional, for consistency across the various configuration systems. Given that, I'd prefer not to correct for it here. Is there any reason you need to set namespaced keys in your environment?

**Comment by ghost** [comment] 2018-12-04 18:58
> Since `:myenv/user` and `:user` are distinct keys, looking them up in a map should yield different results.

In general cases yes, in the case of environment variables, which cannot contain slashes `/` in their name and hence cannot create ambiguity, I disagree. Especially after @weavejester's clarification in weavejester/environ#67 you're basically guaranteed that there will not ever be an entry in `environ.core/env` that contains a slash and hence could be looked up using a namespaced keyword.

> Is there any reason you need to set namespaced keys in your environment?

I am not sure whether it qualifies as a "need", but I tried to make environment variables be easily accessible in my IDE. Typing `::nsalias/` will offer me suggestions and prevent me from accidentally mistyping the env var name and hence getting no or, worse, wrong results. Cursive does not offer the same for non-namespaced keywords.

**Comment by sonntag** [comment] 2018-12-04 19:06
I agree with @aengelberg on this one. If we add this feature then the following will not work, which seems odd to me:

```clj
(ns myenv (:require [envoy.core :refer [defenv]]))
(defenv ::user "The var" :type :string)
(ns other (:require [envoy.core :refer [env]] [myenv :as env]))
(assert (= (::env/user env) 
           (::env/user (into {} env))))
```

**Comment by aengelberg** [comment] 2018-12-04 19:28
@urzds OK, I think I see where you're coming from. For the use case you're describing I'd propose writing a helper function in your own project, like so:

```clojure
(defn env+
  "Like `envoy.core/env` but looks up namespaced keywords as their non-namespaced equivalents."
  [k]
  (envoy.core/env (keyword (name k))))
```

But I think your desire to use namespaced keywords as environ keys is unique enough that it isn't worth baking this into the core library. I'm worried about the confusion I might cause if namespaced keywords are treated as interchangeable aliases of simple keywords, which is not as the language intended.

I'm closing this for now, but open to reconsidering if there is stronger need for a solution or something changes upstream in environ.

**Closed as completed** 2018-12-04 19:28 UTC

**Comment by ghost** [comment] 2018-12-04 20:19
I tried that, but now the `:type` coercion is no longer applied and I get lots of `Access to undeclared env variable :the-var`, because the keyword given to `defenv` and the one given to `env` and `set-env!` do not match anymore.

**Comment by sonntag** [comment] 2018-12-04 21:17
@urzds You could additionally write a helper macro for use at the definition site:

```clj
(require '[envoy.core :as env])
(defmacro defenv+
  [env-key description & {:as opts}]
  `(env/declare-env-var!
     (keyword (name ~env-key))
     (assoc ~opts
            :ns '~(symbol (str *ns*))
            :line ~(:line (meta &form))
            :description ~description)))
```

**Comment by ghost** [comment] 2018-12-05 11:00
Thanks! You changed `defenv+` to this definition, from the first suggestion, because you need to capture `*ns*` and `:line`?

**Comment by sonntag** [comment] 2018-12-05 17:32
That's correct. There may be a way to pass those magic values through with the original definition, but I haven't taken the time to look for it.

**Comment by ghost** [comment] 2019-01-04 13:45
Thank you! We use the following code now:

```clj
(ns my-env
  (:require
   [envoy.core :as envoy]))

(defmacro defenv
  "Like `envoy.core/defenv` but defines namespaced keywords to their non-namespaced equivalents."
  [env-key description & {:as opts}]
  `(envoy/declare-env-var!
    (keyword (name ~env-key))
    (assoc ~opts
           :ns '~(symbol (str *ns*))
           :line ~(:line (meta &form))
           :description ~description)))

(defn env
  "Like `envoy.core/env` but looks up namespaced keywords as their non-namespaced equivalents."
  ([k]
   (envoy/env (keyword (name k))))
  ([k not-found]
   (envoy/env (keyword (name k)) not-found)))

(defn set-env!
  "Like `envoy.core/set-env!` but sets namespaced keywords as their non-namespaced equivalent."
  [k v & kvs]
  (apply envoy/set-env! (keyword (name k)) v kvs))
```
